name: CI

on:
  push:
  pull_request:

jobs:
  # Test the Python package itself
  test_python:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # All Python versions with current Emacs
          - { python-vesion: 3.6,  emacs-version: 29-1 }
          - { python-vesion: 3.7,  emacs-version: 29-1 }
          - { python-vesion: 3.8,  emacs-version: 29-1 }
          - { python-vesion: 3.9,  emacs-version: 29-1 }
          - { python-vesion: 3.10, emacs-version: 29-1 }
          - { python-vesion: 3.11, emacs-version: 29-1 }
          - { python-vesion: 3.12, emacs-version: 29-1 }
          # Current Python with other Emacs
          - { python-vesion: 3.12, emacs-version: 26-3 }
          - { python-vesion: 3.12, emacs-version: 27-2 }
          - { python-vesion: 3.12, emacs-version: 28-2 }
          - { python-vesion: 3.12, emacs-version: snapshot }

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Emacs ${{ matrix.emacs-version }}
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools pytest

    - name: Install package
      run: |
        pip install .

    - name: Test with pytest
      run: |
        pytest
