name: CI

on:
  push:
  pull_request:

jobs:
  # Test the Python package itself
  test_python:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.9
        emacs-version:
          - 24-5
          - 25-3
          - 26-3
          - 27-2
          - snapshot
        # Test older Python versions only with newest version of Emacs
        include:
          - { emacs-version: 27-2, python-version: 3.6 }
          - { emacs-version: 27-2, python-version: 3.7 }
          - { emacs-version: 27-2, python-version: 3.8 }

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Emacs ${{ matrix.emacs-version }}
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools pytest

    - name: Install package
      run: |
        pip install .

    - name: Test with pytest
      run: |
        pytest
